services:
  - type: web
    name: miniRDBMS
    runtime: php
    buildCommand: "mkdir -p /var/data/tables"
    startCommand: php -S 0.0.0.0:$PORT -t web
    envVars:
      - key: PHP_VERSION
        value: 8.2
      - key: STORAGE_PATH
        value: /var/data
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
